aliases:
    oro/filter/gally-filter$: bundles/gallyoro/js/filter/gally-filter
    gallyplugin/js/app/datafilter/gally-multiselect-decorator$: bundles/gallyoro/js/app/datafilter/gally-multiselect-decorator

dynamic-imports:
    orodatagrid:
        - oro/filter/gally-filter
        - gallyplugin/js/app/datafilter/gally-multiselect-decorator

map:
    '*':
        orofilter/js/filters-manager: 'gallyoro/js/filters-manager'
        oroproduct/templates/search-autocomplete.html: 'gallyoro/default/templates/search-autocomplete.html'
    'gallyoro/js/filters-manager':
        'orofilter/js/filters-manager': 'orofilter/js/filters-manager'
